BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Knjige" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"Naziv_knjige"	TEXT NOT NULL,
	"Autor"	TEXT NOT NULL,
	"ISBN"	INTEGER NOT NULL,
	"Kategorija"	TEXT NOT NULL,
	"Izdavač"	TEXT NOT NULL,
	"Izdanje"	TEXT NOT NULL,
	"Jezik"	TEXT NOT NULL,
	"Font"	INTEGER NOT NULL
);
COMMIT;
